### PR TITLE
Adds Pipar Sool outboard

### PR DESCRIPTION
**Pull request by RasmusKoit**
Adds pipar outbooard

### CODE REVIEW

**Comment by RasmusKoit** [comment]
Last test run after commit https://github.com/RasmusKoit/miryoku_zmk/actions/runs/10220343072/job/28280496245

**Comment by RasmusKoit** [comment]
Will keep as draft until I actually have a chance to construct the shield

**Comment by RasmusKoit** [comment]
shield works properly

**Comment by manna-harbour** [comment]
Thanks! This is waiting on the dongle PR to be merged first.

**Comment by manna-harbour** [comment]
Thanks!

**Pull request merged**
