### PR TITLE
Add dao

### PR DESCRIPTION
**Pull request by EgorDuplensky**
Keyboard:
- https://github.com/yumagulovrn/dao-choc-ble

Config:
- https://github.com/yumagulovrn/dao-zmk-config

dao.h is basically a copy of corne.h

### CODE REVIEW

**Comment by manna-harbour** [comment]
Mapping files are named after the board that first introduced the layout, and all keymaps using the same layout just include the one mapping file. So please remove `dao.h` and replace `dao.h` with `corne.h` in `dao.keymap`. Also, the lists in the *Build All* workflows are alphabetical, so please fix the order in `test-all-boards.yml`.

Otherwise, looks great, thanks!

**Comment by EgorDuplensky** [comment]
> Mapping files are named after the board that first introduced the layout, and all keymaps using the same layout just include the one mapping file. So please remove `dao.h` and replace `dao.h` with `corne.h` in `dao.keymap`. Also, the lists in the _Build All_ workflows are alphabetical, so please fix the order in `test-all-boards.yml`.
> 
> Otherwise, looks great, thanks!

Thank you for the comments, applied.
Let me know if I better to squash the commits.

**Comment by manna-harbour** [comment]
No need to squash as I'll do it when I merge anyway.

Please check the commas in the workflow.

**Comment by EgorDuplensky** [comment]
> No need to squash as I'll do it when I merge anyway.
> 
> Please check the commas in the workflow.

My bad, fixed.

**Comment by manna-harbour** [comment]
Thanks!

**Pull request merged**
