### PR TITLE
adds support for dongles

### PR DESCRIPTION
**Pull request by RasmusKoit**
Currently there is a code check for splitting firmware into left and right halves, this code change implements also splitting by _dongle or _central suffix

### CODE REVIEW

**Comment by RasmusKoit** [comment]
Ran a test run with https://github.com/RasmusKoit/miryoku_zmk/actions/runs/10227455196/job/28298921969 for just _left and _right halves

Here is a test run with the same changes + outboard containing a dongle https://github.com/RasmusKoit/miryoku_zmk/actions/runs/10221908453

**Comment by RasmusKoit** [comment]
i am also in the process of writing docs for dongles in the zmk repo [here](https://github.com/zmkfirmware/zmk/pull/2401)

**Comment by manna-harbour** [comment]
Thanks for the PR!

The suffix names aren't explicitly mentioned in your docs, but the examples use only `dongle`. Is `central` just an alternative to that? I guess for ZMK all of the suffix names are just convention, and they can actually be anything.

The workflow requires a list though. Perhaps just one name should be encouraged in the docs (as it is now) and supported in the workflow, for simplicity.

**Comment by RasmusKoit** [comment]
will rework it to use central 👍

**Comment by manna-harbour** [comment]
Is central preferred over dongle? Is there a convention yet?

**Comment by RasmusKoit** [comment]
Actually based on this https://github.com/zmkfirmware/zmk/pull/2525 it seems that dongle will be used instead

**Comment by manna-harbour** [comment]
Thanks!

**Pull request merged**
