### PR TITLE
Add SplitKB Aurora keymaps

### PR DESCRIPTION
**Pull request by bobobo1618**
Sorry if I'm not going about this the right way. These are for SplitKB's variants of Corne and Sweep. The keyboard names should match ZMK. Sweep [is already committed](https://github.com/zmkfirmware/zmk/tree/main/app/boards/shields/splitkb_aurora_sweep) and a branch for Corne [is in the works](https://github.com/petejohanson/zmk/tree/shields/splitkb_aurora_corne).

### CODE REVIEW

**Comment by manna-harbour** [comment]
Nice!

It looks like you haven't set up the author in git?

Also, please add the following lines to `.github/workflows/test-all-promicro-shields.yml` in the appropriate place:
```
        "splitkb_aurora_corne_left","splitkb_aurora_corne_right",
        "splitkb_aurora_sweep_left","splitkb_aurora_sweep_right",
```

**Comment by bobobo1618** [comment]
The lack of author is deliberate, I don't really like putting an email address or name in my public commits because it's resulted in spam before. Do you require an author or are you okay with it as-is?

Added the keyboards to the workflow.

However in testing I've run into a really weird problem: on Sweep at the very least, toggling external power or RGB only affects the left board. It's a key combo that requires pressing keys on both boards, so they're clearly communicating, but something about how Miryoku does it seems to break things.

Any idea how that might happen?

**Comment by manna-harbour** [comment]
> However in testing I've run into a really weird problem: on Sweep at the very least, toggling external power or RGB only affects the left board. It's a key combo that requires pressing keys on both boards, so they're clearly communicating, but something about how Miryoku does it seems to break things.

There's a ZMK issue where locality isn't preserved if the keycode is not used directly in the keymap: https://github.com/zmkfirmware/zmk/issues/1494. In this case EP and RGB are not source specific, but they do use global locality so that the actions are invoked on both sides of a split, so it's likely that the global information is also being lost. To test, replace `&u_out_tog` with `&out OUT_TOG` in https://github.com/manna-harbour/miryoku_zmk/blob/master/miryoku/miryoku_babel/miryoku_layer_alternatives.h. If that's the case I'll have to remove the shift functions for those keys, and make them optional for use on non-spits as with https://github.com/manna-harbour/miryoku_zmk#double-tap-boot.

**Comment by bobobo1618** [comment]
Yep, https://github.com/zmkfirmware/zmk/issues/1494 was the problem. https://github.com/bobobo1618/miryoku_zmk/commit/6ba964f12a9d8138437cffacc487d4827e30fa8f fixed it for me, though the shift combos no longer work of course. 

What would you prefer I do with the author? I can change it to you, to GitHub noreply, or leave it. Up to you.

**Comment by manna-harbour** [comment]
> What would you prefer I do with the author? I can change it to you, to GitHub noreply, or leave it. Up to you.

I'd recommend that you use the GitHub noreply address in general. If you don't want to do that here then please change it to me `Manna Harbour <51143715+manna-harbour@users.noreply.github.com>`.

**Comment by bobobo1618** [comment]
Done, author updated

**Comment by manna-harbour** [comment]
Thanks, merged now.

https://github.com/zmkfirmware/zmk/pull/1504 and https://github.com/zmkfirmware/zmk/pull/1520 are both in ZMK main now.

Here's a sample build run: https://github.com/manna-harbour/miryoku_zmk/actions/runs/3492778615.

**Comment by manna-harbour** [comment]
> Yep, [zmkfirmware/zmk#1494](https://github.com/zmkfirmware/zmk/issues/1494) was the problem. [bobobo1618@6ba964f](https://github.com/bobobo1618/miryoku_zmk/commit/6ba964f12a9d8138437cffacc487d4827e30fa8f) fixed it for me, though the shift combos no longer work of course.

Here's a workaround. It's in a temporary branch for now. https://github.com/manna-harbour/miryoku_zmk/tree/globalshiftfunctions-tmp#global-shift-functions

**Pull request closed without merging**
